### ISSUE TITLE
Action is broken

### ISSUE THREAD

**Issue by 3x071c** [uhyo/please-star-first#18]
From your own action logs:

```
file:///home/runner/work/please-star-first/please-star-first/dist/index.js:1
require('./sourcemap-register.js');module.exports =
^

ReferenceError: require is not defined
    at file:///home/runner/work/please-star-first/please-star-first/dist/index.js:1:1
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by uhyo** [comment]
Thank you for reporting! Fixed.

**Comment by Lissy93** [comment]
Am still [seeing this error](https://github.com/Lissy93/dashy/runs/5466611834) on the latest version, was there anything that needed to be changed in the action file?

**Comment by Lissy93** [comment]
🤦‍♀️ I had totally missed that I'd hard-coded the version, my bad
Thanks for the quick response, and the awesome action :)

**Comment by uhyo** [comment]
Thanks, according to the convention of versioning the `v1` tag should have been updated to point to `v1.0.1`.
It is done now.
